### ISSUE TITLE
Unable to run post_status_update function 

### ISSUE THREAD

**Issue by logankilpatrick** [randyzwitch/Twitter.jl#29]
Here is the error I am getting when running on Julia 1.3:

```
[ Info: Precompiling Twitter [92393bbf-ba23-5323-a3fa-fbe1e5f35af8]
ERROR: LoadError: MethodError: no method matching post_status_update(::String)
Closest candidates are:
  post_status_update(; kwargs...) at /Users/logankilpatrick/.julia/packages/Twitter/4Yzhi/src/macrogenerated.jl:92
```

**Comment by randyzwitch** [comment]
This is really suffering from poor/non-existent documentation. The macro situation happened prior to docstrings, but now it'd be better to just write out all these functions with proper documentation

```julia
post_status_update(status = "Testing from Twitter.jl")
```

https://twitter.com/randyzwitch/status/1206037773284773888
