### ISSUE TITLE
Support automated testing by adding API key

### ISSUE THREAD

**Issue by ggggggggg** [randyzwitch/Twitter.jl#3]
I'm not sure if you care, but I put together a nice way to support automated testing of something that requires an API key. Basically you you `travis encrypt` to get some info for your `travis.yml` file, then the secret info will be available in `ENV` when you run tests on travis.  I wrote up instructions here: https://gist.github.com/ggggggggg/d5e1e3fa8fa614a29f3c

**Comment by randyzwitch** [comment]
Yeah, I have Travis using an authenticated API on a different one of my packages, I just haven't gotten around to it here

**Comment by ggggggggg** [comment]
Ok

**Comment by randyzwitch** [comment]
Fixed by 3509b0d32e8f095b010c97c847293f1eb78c2a66
