### ISSUE TITLE
Getting 403 bad requests when running post status

### ISSUE THREAD

**Issue by logankilpatrick** [randyzwitch/Twitter.jl#30]
Hey! I have been trying to help a few students who are writing Twitter bots using Twitter.jl. 

When I get their code and run it, I always get 403 bad requests. Do you have any idea why this would be? The code is seemingly working for them, and I am trying to validate the completion of the task, but I can't. 

Thanks!

**Comment by randyzwitch** [comment]
What’s the code they are using?

**Comment by logankilpatrick** [comment]
```
using Twitter


twitterauth("aba",
            "aba",
            "aba-aba",
            "aba")

post_status_update(status = "Testing from Twitter.jl")
```

removed the actual data and replaced It with "aba".

**Comment by randyzwitch** [comment]
What you could be running into is the Twitter API rejecting duplicate status updates. If everyone is literally submitting that.

Maybe just have your students write any arbitrary string as an example?

**Comment by logankilpatrick** [comment]
Yep, changing the string did the trick. Thanks! 

Best,
Logan Kilpatrick
