### ISSUE TITLE
get_search_tweets only one tweet

### ISSUE THREAD

**Issue by wakeupqbit** [randyzwitch/Twitter.jl#31]
With the current version I'm able to get only one tweet per query. How do I get more than one ?

**Comment by randyzwitch** [comment]
https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets

If you are getting a successful search, but it only returns a single tweet, I would review the documentation page for the API to see if there are other parameters you are missing. The function itself returns a `Dict`, and within the dict there will be an array of tweets.

**Comment by wakeupqbit** [comment]
I see. Actually, the default 15 it seems to work. However, I always get the same tweet, 15 times the same tweet.

**Comment by wakeupqbit** [comment]
Ohh, my bad. Everything is fine. I was getting each tweet incorrectly from the DataFrame. Thanks!
