### ISSUE TITLE
support "tweet_mode=extended"

### ISSUE THREAD

**Issue by weizlogy** [randyzwitch/Twitter.jl#32]
Long tweet is a specification that is omitted.

To get the unabbreviated tweet, append the query "tweet_mode = extended" to the end of the API URL.

https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

**Comment by stefanjwojcik** [comment]
Specifying 'extended' works for me, just add the tweet mode to the function call. 

```julia-repl
julia> user_t = get_user_timeline(screen_name = "stefanjwojcik", count = 1, tweet_mode = "extended")
```

```julia-repl
julia> user_t_min = get_user_timeline(screen_name = "stefanjwojcik", count = 1)
```

```julia-repl
julia> user_t_min[1]==user_t[1]
false
```

You'll notice that the one with 'extended' has a full text field that reveals the full tweet text rather than truncated.

HTH

**Comment by weizlogy** [comment]
thanks in advice. 
I was able to do it the way I learned from you.

**Comment by randyzwitch** [comment]
This is probably something we should highlight when some proper documentation is written
