### ISSUE TITLE
retweet and favourite information? 

### ISSUE THREAD

**Issue by weijianzhang** [randyzwitch/Twitter.jl#4]
Hi @randyzwitch ,

May I ask, if I can get retweet and favourite information from the Twitter API? 

Thanks,

Weijian

**Comment by randyzwitch** [comment]
Yes, these functions exist. See https://github.com/randyzwitch/Twitter.jl/blob/master/tests/tests.jl for a listing of functions and their arguments.

**Comment by weijianzhang** [comment]
Thanks @randyzwitch
