### ISSUE TITLE
Twitter.jl fails to build on M1 Mac

### ISSUE THREAD

**Issue by logankilpatrick** [randyzwitch/Twitter.jl#48]
Posted this question here: https://stackoverflow.com/questions/72209061/how-to-install-a-julia-package-if-it-fails-to-install-build-on-an-m1-mac as well, trying to get this resolved

**Comment by gbaraldi** [comment]
The issue is that the current compat allows using OAuth 0.7 which gets an old MbedTLS which needs binaryprovider.
