### ISSUE TITLE
Problems with parse()

### ISSUE THREAD

**Issue by DataWookie** [randyzwitch/Twitter.jl#6]
Hi!

I planned on giving your Twitter package a whirl today (having had some good experiences with a similar package in R), but I ran into a bit of a problem. Authentication went fine but then when I tried a range of functions I ended up getting the same error message:

    julia> get_mentions_timeline();
    ERROR: `parse` has no method matching parse(::Array{Uint8,1})
    julia> get_retweets_id("434685122671939584")
    ERROR: `parse` has no method matching parse(::Array{Uint8,1})
     in get_retweets_id at /home/colliera/.julia/v0.3/Twitter/src/tweets.jl:13
    julia> get_help_languages()
    ERROR: `parse` has no method matching parse(::Array{Uint8,1})
    julia> get_lists()
    ERROR: `parse` has no method matching parse(::Array{Uint8,1})

Do you have an idea what the issue might be? I am running Julia 0.3.10 (2015-06-24 13:54 UTC) on a 64 bit Linux machine. The Twitter package was installed fresh today using Pkg.add().

Best regards,
Andrew.

**Comment by randyzwitch** [comment]
Thanks for reporting. The parse() function comes from the JSON package I think, so I'll have to investigate what the problem might be.

**Comment by DataWookie** [comment]
Thanks for getting back to me. Right, if it is of any help, I am running version 0.4.5 of the JSON package.

**Comment by randyzwitch** [comment]
It's broken on 0.4-dev too, so it's just plain broken from upstream changes.

I'll try to get this fixed this week.

**Comment by DataWookie** [comment]
Thank you, that would be great!

**Comment by randyzwitch** [comment]
Good news/bad news. Should be fixed on master, so if you could do `Pkg.checkout("Twitter")` before I commit a new version to METADATA, that would be helpful.

Unfortunately, you have to use v0.4, as one of my dependencies went 0.4 only (the Requests library, where the error you reported stemmed from).

**Comment by randyzwitch** [comment]
I *think* this is solved, now that 0.4 is the stable version. Comment if a good `Pkg.update()` doesn't solve the problem.
